version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "manual-fraud-inference"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12kj3q6fmd7x7"
s3_prefix = "manual-fraud-inference"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["InferenceFunction=049117409129.dkr.ecr.us-east-1.amazonaws.com/manual-fraud-inference"]
